# Introduction to NumPy Arrays

## Import

In [4]:
import numpy as np

## Introduction

Until now we have been using lists as a way of storing multiple elements together. However, when doing numerical computations, lists are not very good. For example, what if I wanted to add one to a list of numbers? For a list ```a = [1, 2, 3]``` we can not write ```a + 1```.

Instead we would have to do

In [5]:
a = [1, 2, 3]
for k in range(3):
    a[k] = a[k] + 1
a

[2, 3, 4]

Working with lists would quickly become very complicated if we wanted to do numerical operations on many elements at the same time, or if, for example, we want to be able to construct vectors and matrices in our programs. All of these features, and more, come with using NumPy arrays as our preferred data structure.

## NumPy Arrays

When dealing with numerical data in Python, nearly 100% of the time one uses arrays from the NumPy module to store and manipulate data. NumPy arrays are very similar to Python lists, but are actually arrays in c-code that allow for very fast multi-dimensional numerical, vector, matrix, and linear algebra operations. Using arrays with slicing, and **vectorization** leads to very fast Python code, and can replace many of the for-loops that you would have use if you coded a problem using lists. As a general rule, **minimizing the number of for-loops maximizes the performance of your code**. To start using arrays, we can start with a simple list and use it as an argument to the array function

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


We have now created our first array of integers. Notice how, when using print, the array looks the same as a list, however it is very much a different data structure. We can also create an array of floats, complex numbers or even strings

In [7]:
a = np.array([2.0, 4.0, 8.0, 16.0])
b = np.array([0, 1 + 0j, 1 + 1j, 2 - 2j])
c = np.array(["a", "b", "c", "d"])
print(a)
print(b)
print(c)

[ 2.  4.  8. 16.]
[0.+0.j 1.+0.j 1.+1.j 2.-2.j]
['a' 'b' 'c' 'd']


In general there are three different ways of creating arrays in Python:

- First create a list and then call the array function using the list as an input argument.

- Use NumPy functions that are designed to create arrays: zeros, ones, arange, linspace.

- Import data into Python from file.

### Arrays from Lists

We have already seen how to create arrays with simple lists, but now lets look at how to create more complicated lists that we can turn into arrays. A short way of creating a list, say from 0 to 9 is as follows:

In [8]:
output = [n for n in range(10)]
print(output)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


This code is doing the exact same thing as the longer expression

In [9]:
output = []
for n in range(10):
    output.append(n)
print(output)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


We could turn this into an array quite easy

In [10]:
np.array(output)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Or, we can save even more space and create the list inside of the array function:

In [11]:
np.array([n for n in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This can also be used to create more complicated arrays

In [14]:
np.array([2.0 * k**0.563 for k in range(0, 10, 2)])

array([0.        , 2.95467613, 4.36505551, 5.48440035, 6.44866265])

### Array Creation in NumPy

NumPy has several extremely important array creation functions that will make your life much easier.
For example, creating arrays of all zeros or ones in trivial.

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

However, the most useful functions are **```arange```** which generates evenly spaces values within a given interval in a similar way that the ```range``` function did, and **```linspace```** that makes a linear array of points from a starting to an ending value.

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
# make an array of 20 points linearly spaced from 0 to 10
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
np.linspace(-5, 5, 15)  # 15 points in range from -5 to 5

array([-5.        , -4.28571429, -3.57142857, -2.85714286, -2.14285714,
       -1.42857143, -0.71428571,  0.        ,  0.71428571,  1.42857143,
        2.14285714,  2.85714286,  3.57142857,  4.28571429,  5.        ])